[2025-02-23T04:34:47.630+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:34:47.678+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-10-10T00:00:00+00:00 [queued]>
[2025-02-23T04:34:47.698+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-10-10T00:00:00+00:00 [queued]>
[2025-02-23T04:34:47.700+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:34:47.780+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2021-10-10 00:00:00+00:00
[2025-02-23T04:34:47.792+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5086) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:34:47.794+0000] {standard_task_runner.py:72} INFO - Started process 5096 to run task
[2025-02-23T04:34:47.794+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2021-10-10T00:00:00+00:00', '--job-id', '1126', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp4i4yoqfl']
[2025-02-23T04:34:47.801+0000] {standard_task_runner.py:105} INFO - Job 1126: Subtask second_task
[2025-02-23T04:34:47.897+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2021-10-10T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:34:48.075+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-10T00:00:00+00:00'
[2025-02-23T04:34:48.076+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:34:48.115+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:34:48.117+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:34:48.136+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:34:48.138+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:34:48.140+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:34:48.190+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:34:48.192+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2021-10-10T00:00:00+00:00, execution_date=20211010T000000, start_date=20250223T043447, end_date=20250223T043448
[2025-02-23T04:34:48.416+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:34:48.457+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:34:48.465+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
