[2025-02-23T04:38:21.736+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:38:21.777+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2025-02-23T04:38:21.803+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2025-02-23T04:38:21.805+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:38:21.947+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2022-11-10 00:00:00+00:00
[2025-02-23T04:38:21.963+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8323) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:38:21.967+0000] {standard_task_runner.py:72} INFO - Started process 8336 to run task
[2025-02-23T04:38:21.964+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2022-11-10T00:00:00+00:00', '--job-id', '1918', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp9o38stat']
[2025-02-23T04:38:21.970+0000] {standard_task_runner.py:105} INFO - Job 1918: Subtask second_task
[2025-02-23T04:38:22.068+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2022-11-10T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:38:22.255+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-10T00:00:00+00:00'
[2025-02-23T04:38:22.257+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:38:22.294+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:38:22.296+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:38:22.316+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:38:22.319+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:38:22.320+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:38:22.369+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:38:22.371+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2022-11-10T00:00:00+00:00, execution_date=20221110T000000, start_date=20250223T043821, end_date=20250223T043822
[2025-02-23T04:38:22.467+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:38:22.504+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:38:22.508+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
