[2025-02-23T04:32:20.355+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:32:20.413+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-02-05T00:00:00+00:00 [queued]>
[2025-02-23T04:32:20.439+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-02-05T00:00:00+00:00 [queued]>
[2025-02-23T04:32:20.441+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:32:20.577+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2021-02-05 00:00:00+00:00
[2025-02-23T04:32:20.593+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3049) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:32:20.596+0000] {standard_task_runner.py:72} INFO - Started process 3064 to run task
[2025-02-23T04:32:20.597+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2021-02-05T00:00:00+00:00', '--job-id', '632', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpgb44vrr4']
[2025-02-23T04:32:20.601+0000] {standard_task_runner.py:105} INFO - Job 632: Subtask second_task
[2025-02-23T04:32:20.732+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2021-02-05T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:32:20.924+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-02-05T00:00:00+00:00'
[2025-02-23T04:32:20.930+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:32:20.963+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:32:20.964+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:32:20.987+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:32:20.990+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:32:20.991+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:32:21.054+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:32:21.056+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2021-02-05T00:00:00+00:00, execution_date=20210205T000000, start_date=20250223T043220, end_date=20250223T043221
[2025-02-23T04:32:21.222+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:32:21.256+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:32:21.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
