[2025-02-23T04:34:36.134+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:34:36.178+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-09-25T00:00:00+00:00 [queued]>
[2025-02-23T04:34:36.202+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-09-25T00:00:00+00:00 [queued]>
[2025-02-23T04:34:36.204+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:34:36.236+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2021-09-25 00:00:00+00:00
[2025-02-23T04:34:36.249+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4945) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:34:36.249+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2021-09-25T00:00:00+00:00', '--job-id', '1092', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmph9kxt7qe']
[2025-02-23T04:34:36.252+0000] {standard_task_runner.py:72} INFO - Started process 4953 to run task
[2025-02-23T04:34:36.252+0000] {standard_task_runner.py:105} INFO - Job 1092: Subtask second_task
[2025-02-23T04:34:36.346+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2021-09-25T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:34:36.522+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-25T00:00:00+00:00'
[2025-02-23T04:34:36.524+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:34:36.562+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:34:36.566+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:34:36.583+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:34:36.586+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:34:36.587+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:34:36.632+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:34:36.634+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2021-09-25T00:00:00+00:00, execution_date=20210925T000000, start_date=20250223T043436, end_date=20250223T043436
[2025-02-23T04:34:36.713+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:34:36.745+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:34:36.750+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
