[2025-02-23T04:34:03.003+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:34:03.044+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-07-28T00:00:00+00:00 [queued]>
[2025-02-23T04:34:03.070+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-07-28T00:00:00+00:00 [queued]>
[2025-02-23T04:34:03.074+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:34:03.102+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2021-07-28 00:00:00+00:00
[2025-02-23T04:34:03.117+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4455) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:34:03.121+0000] {standard_task_runner.py:72} INFO - Started process 4469 to run task
[2025-02-23T04:34:03.118+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2021-07-28T00:00:00+00:00', '--job-id', '974', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpasn2vmmf']
[2025-02-23T04:34:03.123+0000] {standard_task_runner.py:105} INFO - Job 974: Subtask second_task
[2025-02-23T04:34:03.213+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2021-07-28T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:34:03.393+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-07-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-07-28T00:00:00+00:00'
[2025-02-23T04:34:03.395+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:34:03.430+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:34:03.434+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:34:03.449+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:34:03.451+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:34:03.452+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:34:03.497+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:34:03.499+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2021-07-28T00:00:00+00:00, execution_date=20210728T000000, start_date=20250223T043403, end_date=20250223T043403
[2025-02-23T04:34:03.580+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:34:03.616+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:34:03.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
