[2025-02-23T04:33:04.916+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:33:04.958+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-04-20T00:00:00+00:00 [queued]>
[2025-02-23T04:33:04.980+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-04-20T00:00:00+00:00 [queued]>
[2025-02-23T04:33:04.982+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:33:05.012+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2021-04-20 00:00:00+00:00
[2025-02-23T04:33:05.027+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3655) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:33:05.029+0000] {standard_task_runner.py:72} INFO - Started process 3667 to run task
[2025-02-23T04:33:05.028+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2021-04-20T00:00:00+00:00', '--job-id', '779', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpsxqx3h3n']
[2025-02-23T04:33:05.031+0000] {standard_task_runner.py:105} INFO - Job 779: Subtask second_task
[2025-02-23T04:33:05.137+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2021-04-20T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:33:05.434+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-20T00:00:00+00:00'
[2025-02-23T04:33:05.436+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:33:05.478+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:33:05.480+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:33:05.498+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:33:05.501+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:33:05.503+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:33:05.564+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:33:05.565+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2021-04-20T00:00:00+00:00, execution_date=20210420T000000, start_date=20250223T043304, end_date=20250223T043305
[2025-02-23T04:33:05.694+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:33:05.722+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:33:05.726+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
