[2025-02-23T04:32:33.953+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:32:34.015+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.first_task scheduled__2021-03-06T00:00:00+00:00 [queued]>
[2025-02-23T04:32:34.040+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.first_task scheduled__2021-03-06T00:00:00+00:00 [queued]>
[2025-02-23T04:32:34.044+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:32:34.169+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2021-03-06 00:00:00+00:00
[2025-02-23T04:32:34.181+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:32:34.184+0000] {standard_task_runner.py:72} INFO - Started process 3257 to run task
[2025-02-23T04:32:34.182+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'first_task', 'scheduled__2021-03-06T00:00:00+00:00', '--job-id', '679', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp0lg2l07v']
[2025-02-23T04:32:34.187+0000] {standard_task_runner.py:105} INFO - Job 679: Subtask first_task
[2025-02-23T04:32:34.283+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.first_task scheduled__2021-03-06T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:32:34.471+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-03-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-03-06T00:00:00+00:00'
[2025-02-23T04:32:34.473+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:32:34.521+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:32:34.523+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Hello World!' This is the first Task"]
[2025-02-23T04:32:34.546+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:32:34.549+0000] {subprocess.py:106} INFO - Hello World! This is the first Task
[2025-02-23T04:32:34.550+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:32:34.605+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:32:34.607+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=first_task, run_id=scheduled__2021-03-06T00:00:00+00:00, execution_date=20210306T000000, start_date=20250223T043234, end_date=20250223T043234
[2025-02-23T04:32:34.686+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:32:34.744+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:32:34.748+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
