[2025-02-23T04:37:35.932+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:37:35.976+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2022-08-23T00:00:00+00:00 [queued]>
[2025-02-23T04:37:35.996+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2022-08-23T00:00:00+00:00 [queued]>
[2025-02-23T04:37:35.999+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:37:36.034+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2022-08-23 00:00:00+00:00
[2025-02-23T04:37:36.049+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7666) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:37:36.047+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2022-08-23T00:00:00+00:00', '--job-id', '1754', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp1cn606ej']
[2025-02-23T04:37:36.052+0000] {standard_task_runner.py:105} INFO - Job 1754: Subtask second_task
[2025-02-23T04:37:36.052+0000] {standard_task_runner.py:72} INFO - Started process 7668 to run task
[2025-02-23T04:37:36.148+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2022-08-23T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:37:36.376+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-08-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-23T00:00:00+00:00'
[2025-02-23T04:37:36.378+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:37:36.419+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:37:36.422+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:37:36.435+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:37:36.440+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:37:36.442+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:37:36.489+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:37:36.491+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2022-08-23T00:00:00+00:00, execution_date=20220823T000000, start_date=20250223T043735, end_date=20250223T043736
[2025-02-23T04:37:36.596+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:37:36.625+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:37:36.630+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
