[2025-02-23T04:30:44.603+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:30:44.634+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2025-02-23T04:30:44.652+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2025-02-23T04:30:44.654+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:30:44.687+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2022-05-02 00:00:00+00:00
[2025-02-23T04:30:44.703+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2315) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:30:44.705+0000] {standard_task_runner.py:72} INFO - Started process 2322 to run task
[2025-02-23T04:30:44.703+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2022-05-02T00:00:00+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpfcm1mqcw']
[2025-02-23T04:30:44.707+0000] {standard_task_runner.py:105} INFO - Job 457: Subtask first_task
[2025-02-23T04:30:44.802+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2022-05-02T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:30:44.974+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2022-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-02T00:00:00+00:00'
[2025-02-23T04:30:44.976+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:30:45.010+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:30:45.012+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Hello World!' This is the first Task"]
[2025-02-23T04:30:45.027+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:30:45.030+0000] {subprocess.py:106} INFO - Hello World! This is the first Task
[2025-02-23T04:30:45.032+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:30:45.085+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:30:45.086+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=scheduled__2022-05-02T00:00:00+00:00, execution_date=20220502T000000, start_date=20250223T043044, end_date=20250223T043045
[2025-02-23T04:30:45.164+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:30:45.208+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:30:45.214+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
