[2025-02-23T04:28:55.993+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:28:56.024+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2021-08-30T00:00:00+00:00 [queued]>
[2025-02-23T04:28:56.040+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2021-08-30T00:00:00+00:00 [queued]>
[2025-02-23T04:28:56.042+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:28:56.075+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2021-08-30 00:00:00+00:00
[2025-02-23T04:28:56.091+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1289) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:28:56.093+0000] {standard_task_runner.py:72} INFO - Started process 1299 to run task
[2025-02-23T04:28:56.091+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2021-08-30T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmplkqy3eex']
[2025-02-23T04:28:56.094+0000] {standard_task_runner.py:105} INFO - Job 212: Subtask first_task
[2025-02-23T04:28:56.179+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2021-08-30T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:28:56.358+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-08-30T00:00:00+00:00'
[2025-02-23T04:28:56.359+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:28:56.394+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:28:56.396+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Hello World!' This is the first Task"]
[2025-02-23T04:28:56.415+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:28:56.418+0000] {subprocess.py:106} INFO - Hello World! This is the first Task
[2025-02-23T04:28:56.419+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:28:56.464+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:28:56.467+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=scheduled__2021-08-30T00:00:00+00:00, execution_date=20210830T000000, start_date=20250223T042856, end_date=20250223T042856
[2025-02-23T04:28:56.552+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:28:56.583+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:28:56.587+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
