[2025-02-23T04:36:16.446+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:36:16.487+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2022-03-30T00:00:00+00:00 [queued]>
[2025-02-23T04:36:16.508+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2022-03-30T00:00:00+00:00 [queued]>
[2025-02-23T04:36:16.510+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:36:16.537+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2022-03-30 00:00:00+00:00
[2025-02-23T04:36:16.552+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6474) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:36:16.551+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2022-03-30T00:00:00+00:00', '--job-id', '1465', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpo670_kon']
[2025-02-23T04:36:16.555+0000] {standard_task_runner.py:72} INFO - Started process 6484 to run task
[2025-02-23T04:36:16.555+0000] {standard_task_runner.py:105} INFO - Job 1465: Subtask second_task
[2025-02-23T04:36:16.647+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2022-03-30T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:36:16.814+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-30T00:00:00+00:00'
[2025-02-23T04:36:16.816+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:36:16.844+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:36:16.846+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:36:16.864+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:36:16.867+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:36:16.868+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:36:16.916+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:36:16.917+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2022-03-30T00:00:00+00:00, execution_date=20220330T000000, start_date=20250223T043616, end_date=20250223T043616
[2025-02-23T04:36:16.974+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:36:17.005+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:36:17.010+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
