[2025-02-23T04:33:56.436+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:33:56.486+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-07-14T00:00:00+00:00 [queued]>
[2025-02-23T04:33:56.517+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2021-07-14T00:00:00+00:00 [queued]>
[2025-02-23T04:33:56.519+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:33:56.582+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2021-07-14 00:00:00+00:00
[2025-02-23T04:33:56.604+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4350) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:33:56.609+0000] {standard_task_runner.py:72} INFO - Started process 4360 to run task
[2025-02-23T04:33:56.605+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2021-07-14T00:00:00+00:00', '--job-id', '948', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp4_d78fho']
[2025-02-23T04:33:56.613+0000] {standard_task_runner.py:105} INFO - Job 948: Subtask second_task
[2025-02-23T04:33:56.740+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2021-07-14T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:33:56.958+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-07-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-07-14T00:00:00+00:00'
[2025-02-23T04:33:56.962+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:33:56.997+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:33:57.000+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Second task will run after first task']
[2025-02-23T04:33:57.019+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:33:57.022+0000] {subprocess.py:106} INFO - Second task will run after first task
[2025-02-23T04:33:57.024+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:33:57.070+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:33:57.072+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2021-07-14T00:00:00+00:00, execution_date=20210714T000000, start_date=20250223T043356, end_date=20250223T043357
[2025-02-23T04:33:57.154+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:33:57.193+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:33:57.197+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
